# Generated by Django 5.0.4 on 2024-05-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vender', '0005_vender_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Vender', 'Vender')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
