# Generated by Django 5.0.4 on 2024-05-06 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vender', '0006_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vender',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vender_useraccount', to=settings.AUTH_USER_MODEL),
        ),
    ]
