# Generated by Django 5.0.4 on 2024-05-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
