# Generated by Django 5.0.4 on 2024-05-06 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0002_alter_purchase_order_date'),
        ('Vender', '0007_alter_vender_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vender_purchase', to='Vender.vender'),
            preserve_default=False,
        ),
    ]
