# Generated by Django 5.0.4 on 2024-05-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0003_purchase_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='po_number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Aknowledged', "'Aknowledged")], default='Pending', max_length=50),
        ),
    ]
