# Generated by Django 5.0.4 on 2024-05-06 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0004_alter_purchase_po_number_alter_purchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='acknowledgment_date',
            field=models.DateTimeField(default=datetime.datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 6, 22, 22, 40, 362808)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='quality_rating',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='order_date',
            field=models.DateTimeField(),
        ),
    ]
