# Generated by Django 5.0.4 on 2024-05-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0005_purchase_acknowledgment_date_purchase_issue_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='quality_rating',
            field=models.FloatField(default=0),
        ),
    ]
