# Generated by Django 5.0.4 on 2024-05-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0006_alter_purchase_quality_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='acknowledgment_date',
            field=models.DateTimeField(null=True),
        ),
    ]
