# Generated by Django 5.0.4 on 2024-05-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0008_purchasestatuslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='completed_date',
            field=models.DateTimeField(null=True),
        ),
    ]
